pipeline {
    agent any

    environment {
        GIT_CREDENTIALS = 'github-credentials'
        VENV = '.venv'
    }

    stages {
        stage('Clone Repo') {
            steps {
                git credentialsId: "${GIT_CREDENTIALS}", url: 'https://github.com/Vinnieotieno/alx-backend-python.git'
            }
        }
        stage('Install Dependencies') {
            steps {
                sh '''
                    python3 -m venv ${VENV}
                    . ${VENV}/bin/activate
                    pip install --upgrade pip
                    pip install -r messaging_app/requirements.txt
                '''
            }
        }
        stage('Run Tests') {
            steps {
                sh '''
                    . ${VENV}/bin/activate
                    pytest --junitxml=messaging_app/test-results.xml
                '''
            }
        }
        stage('Publish Report') {
            steps {
                junit 'messaging_app/test-results.xml'
            }
        }
    }
}
