pipeline {
    agent any

    environment {
        GIT_CREDENTIALS = 'github-credentials'
        VENV = '.venv'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', credentialsId: "${GIT_CREDENTIALS}", url: 'https://github.com/Vinnieotieno/alx-backend-python.git'
                sh 'git branch'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                    python3 -m venv ${VENV}
                    . ${VENV}/bin/activate
                    pip3 install --upgrade pip
                    pip3 install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    . ${VENV}/bin/activate
                    pytest messaging_app/ --junitxml=messaging_app/test-results.xml
                '''
            }
        }

        stage('Publish Test Report') {
            steps {
                junit 'messaging_app/test-results.xml'
            }
        }
    }
}
