#!/bin/bash

echo "Applying blue deployment..."
kubectl apply -f messaging_app/blue_deployment.yaml

echo "Applying green deployment..."
kubectl apply -f messaging_app/green_deployment.yaml

echo "Applying service..."
kubectl apply -f messaging_app/kubeservice.yaml

echo "Checking logs..."
kubectl logs -l app=messaging-app-green
